<?php
/**
 * Villa ACF field group — PHP registration (`acf_add_local_field_group`).
 *
 * Consolidates the six legacy groups (Villa ID / Villa / Villa Required /
 * Villa Information / Villa Prices / Villa Special Offers) into a single
 * group with left-placed tabs, matching the homepage and about-page admin
 * pattern. Every field's original `key` and `name` is preserved so existing
 * villa data continues to load — only the visual organisation changes.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers the villa data-layer field group.
 *
 * Hooks at priority 15 so mu-plugin baseline Site Options
 * (register-options.php) can run first when both use `acf/init`.
 *
 * @since 3b
 */
function ibv_register_villa_acf_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key'                   => 'group_ibv_villa',
		'title'                 => __( 'Villa', 'ibv' ),
		'fields'                => array(

			// ─── Tab: Identity ──────────────────────────────────────────
			array(
				'key'       => 'field_ibv_villa_tab_identity',
				'label'     => __( 'Identity', 'ibv' ),
				'type'      => 'tab',
				'placement' => 'left',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_5582ae34eee06',
				'label'                => 'Property ID',
				'name'                 => 'property_id',
				'aria-label'           => '',
				'type'                 => 'text',
				'instructions'         => 'Do not modify this area unless you know what you are doing - this matches up with the availability system.',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'maxlength'            => '',
				'readonly'             => 0,
				'disabled'             => 0,
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => 0,
				'allow_quickedit'      => 0,
				'show_column'          => 0,
				'show_column_weight'   => 0,
				'show_column_sortable' => false,
				'key'                  => 'field_5849d0c9962f6',
				'label'                => 'Villa Pretty Name',
				'name'                 => 'villa_pretty_name',
				'aria-label'           => '',
				'type'                 => 'text',
				'instructions'         => 'such as "Villa Tom"',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'maxlength'            => '',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => 0,
				'allow_quickedit'      => 0,
				'show_column'          => 0,
				'show_column_weight'   => 1000,
				'show_column_sortable' => 0,
				'key'                  => 'field_58c80b31fb5ea',
				'label'                => 'additional_title_keyword for H1',
				'name'                 => 'additional_title_keyword',
				'aria-label'           => '',
				'type'                 => 'text',
				'instructions'         => 'this text is appended after villa pretty name title in the villa page.',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'maxlength'            => '',
			),

			// ─── Tab: Key facts ─────────────────────────────────────────
			array(
				'key'       => 'field_ibv_villa_tab_key_facts',
				'label'     => __( 'Key facts', 'ibv' ),
				'type'      => 'tab',
				'placement' => 'left',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => 0,
				'allow_quickedit'      => 0,
				'show_column'          => 0,
				'show_column_weight'   => 0,
				'show_column_sortable' => false,
				'key'                  => 'field_557982a7e2516',
				'label'                => 'Property Sleeps UK',
				'name'                 => 'property_sleeps',
				'aria-label'           => '',
				'type'                 => 'number',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'min'                  => '',
				'max'                  => 40,
				'step'                 => '',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_57a9f17acad6c',
				'label'                => 'Property Bedrooms UK',
				'name'                 => 'property_bedrooms',
				'aria-label'           => '',
				'type'                 => 'number',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'min'                  => '',
				'max'                  => '',
				'step'                 => '',
				'readonly'             => 0,
				'disabled'             => 0,
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_57a9f1df13490',
				'label'                => 'Property Bathrooms UK',
				'name'                 => 'property_bathrooms',
				'aria-label'           => '',
				'type'                 => 'number',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'min'                  => '',
				'max'                  => '',
				'step'                 => '',
				'readonly'             => 0,
				'disabled'             => 0,
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_558012ac8b4ef',
				'label'                => 'Property Featured',
				'name'                 => 'property_featured',
				'aria-label'           => '',
				'type'                 => 'true_false',
				'instructions'         => 'Is this a featured property?',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'              => '',
				'default_value'        => 0,
				'ui'                   => 0,
				'ui_on_text'           => '',
				'ui_off_text'          => '',
			),
			array(
				'key'          => 'field_ibv_villa_rating_score',
				'label'        => __( 'Rating score', 'ibv' ),
				'name'         => 'villa_rating_score',
				'type'         => 'number',
				'min'          => 0,
				'max'          => 5,
				'step'         => 0.1,
				'instructions' => __( 'Optional. e.g. 4.9', 'ibv' ),
			),
			array(
				'key'   => 'field_ibv_villa_review_count',
				'label' => __( 'Review count', 'ibv' ),
				'name'  => 'villa_review_count',
				'type'  => 'number',
				'min'   => 0,
				'step'  => 1,
			),
			array(
				'key'   => 'field_ibv_villa_review_source_url',
				'label' => __( 'Review source URL', 'ibv' ),
				'name'  => 'villa_review_source_url',
				'type'  => 'url',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_5d2c7c2a4337d',
				'label'                => 'Notice UK',
				'name'                 => 'notice_uk',
				'aria-label'           => '',
				'type'                 => 'text',
				'instructions'         => '',
				'required'             => 1,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => 'If you are a large group of 12 or more people please email us at bookings@ibizavillas2000.com',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'maxlength'            => '',
			),

			// ─── Tab: Content ───────────────────────────────────────────
			array(
				'key'       => 'field_ibv_villa_tab_content',
				'label'     => __( 'Content', 'ibv' ),
				'type'      => 'tab',
				'placement' => 'left',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_5579a38eaa707',
				'label'                => 'Property Location',
				'name'                 => 'property_summary',
				'aria-label'           => '',
				'type'                 => 'wysiwyg',
				'instructions'         => 'Enter simple sentences or bullet point lists.',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'tabs'                 => 'all',
				'toolbar'              => 'full',
				'media_upload'         => 1,
				'delay'                => 0,
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_5582c42f4c3b4',
				'label'                => 'Property Facts',
				'name'                 => 'property_features',
				'aria-label'           => '',
				'type'                 => 'repeater',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'collapsed'            => '',
				'min'                  => 0,
				'max'                  => 0,
				'layout'               => 'table',
				'button_label'         => 'Add Feature',
				'sub_fields'           => array(
					array(
						'allow_backendsearch'  => false,
						'show_column_filter'   => false,
						'allow_bulkedit'       => 0,
						'allow_quickedit'      => 0,
						'show_column'          => 0,
						'show_column_weight'   => 1000,
						'show_column_sortable' => 0,
						'key'                  => 'field_5582c4cf4c3b5',
						'label'                => 'Property Facts Icon',
						'name'                 => 'property_feature_icon',
						'aria-label'           => '',
						'type'                 => 'select',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '25',
							'class' => '',
							'id'    => '',
						),
						'choices'              => array(
							'property-bed-icon'    => 'Bed',
							'property-people-icon' => 'People',
							'property-star-icon'   => 'Star',
							'property-car-icon'    => 'Car',
							'property-bus-icon'    => 'Bus',
							'property-dot-icon'    => 'Dot',
							'property-village-icon' => 'Village',
							'property-tv-icon'     => 'TV',
							'wifi'                 => 'Wifi',
							'Superficie-total'     => 'Superficie-total',
							'Jardín'               => 'Jardín',
							'Piscina'              => 'Piscina',
							'Aire acondicionado'   => 'Aire acondicionado',
							'Calefacción'          => 'Calefacción',
							'Número plantas'       => 'Número plantas',
							'Hab. dobles'          => 'Hab. dobles',
						),
						'default_value'        => false,
						'allow_null'           => 0,
						'multiple'             => 0,
						'ui'                   => 0,
						'return_format'        => 'value',
						'ajax'                 => 0,
						'placeholder'          => '',
						'create_options'       => 0,
						'save_options'         => 0,
						'parent_repeater'      => 'field_5582c42f4c3b4',
					),
					array(
						'allow_backendsearch'  => false,
						'show_column_filter'   => false,
						'allow_bulkedit'       => false,
						'allow_quickedit'      => false,
						'show_column'          => false,
						'show_column_weight'   => 1000,
						'show_column_sortable' => false,
						'key'                  => 'field_5582c5514c3b6',
						'label'                => 'Property Facts Text',
						'name'                 => 'property_feature_text',
						'aria-label'           => '',
						'type'                 => 'text',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => 75,
							'class' => '',
							'id'    => '',
						),
						'default_value'        => '',
						'placeholder'          => '',
						'prepend'              => '',
						'append'               => '',
						'maxlength'            => '',
						'readonly'             => 0,
						'disabled'             => 0,
						'parent_repeater'      => 'field_5582c42f4c3b4',
					),
				),
				'rows_per_page'        => 20,
			),
			// ─── Tab: Media ─────────────────────────────────────────────
			array(
				'key'       => 'field_ibv_villa_tab_media',
				'label'     => __( 'Media', 'ibv' ),
				'type'      => 'tab',
				'placement' => 'left',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_55799b13e3584',
				'label'                => 'Property Image Gallery',
				'name'                 => 'property_images',
				'aria-label'           => '',
				'type'                 => 'gallery',
				'instructions'         => 'Landscape or mixed-aspect photos. The pop-up viewer holds images at source shape, so portrait shots display correctly here too.',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'min'                  => '',
				'max'                  => '',
				'preview_size'         => 'thumbnail',
				'library'              => 'all',
				'min_width'            => '',
				'min_height'           => '',
				'min_size'             => '',
				'max_width'            => '',
				'max_height'           => '',
				'max_size'             => '',
				'mime_types'           => '',
				'return_format'        => 'array',
				'insert'               => 'append',
			),

			// ─── Tab: Location ──────────────────────────────────────────
			array(
				'key'       => 'field_ibv_villa_tab_location',
				'label'     => __( 'Location', 'ibv' ),
				'type'      => 'tab',
				'placement' => 'left',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_558065ef4f993',
				'label'                => 'Property Map',
				'name'                 => 'property_map',
				'aria-label'           => '',
				'type'                 => 'google_map',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'center_lat'           => '45.923697',
				'center_lng'           => '6.869433',
				'zoom'                 => 7,
				'height'               => '',
			),
			array(
				'key'          => 'field_ibv_villa_distances',
				'label'        => __( 'Distance ticks', 'ibv' ),
				'name'         => 'villa_distances',
				'type'         => 'repeater',
				'layout'       => 'block',
				'button_label' => __( 'Add distance', 'ibv' ),
				'sub_fields'   => array(
					array(
						'key'             => 'field_ibv_villa_distance_poi',
						'label'           => __( 'Place of interest (taxonomy)', 'ibv' ),
						'name'            => 'poi',
						'type'            => 'taxonomy',
						'taxonomy'        => 'villa_poi',
						'field_type'      => 'select',
						'allow_null'      => 0,
						'return_format'   => 'object',
						'multiple'        => 0,
						'parent_repeater' => 'field_ibv_villa_distances',
					),
					array(
						'key'             => 'field_ibv_villa_distance_text',
						'label'           => __( 'Distance text', 'ibv' ),
						'name'            => 'distance_text',
						'type'            => 'text',
						'parent_repeater' => 'field_ibv_villa_distances',
					),
				),
			),

			// ─── Tab: Pricing ───────────────────────────────────────────
			array(
				'key'       => 'field_ibv_villa_tab_pricing',
				'label'     => __( 'Pricing', 'ibv' ),
				'type'      => 'tab',
				'placement' => 'left',
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_56586f094a324',
				'label'                => 'Property Price From (Euros)',
				'name'                 => 'property_price_from_euros',
				'aria-label'           => '',
				'type'                 => 'number',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'min'                  => '',
				'max'                  => '',
				'step'                 => '',
				'readonly'             => 0,
				'disabled'             => 0,
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_56586f1a4a325',
				'label'                => 'Property Price To (Euros)',
				'name'                 => 'property_price_to_euros',
				'aria-label'           => '',
				'type'                 => 'number',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'min'                  => '',
				'max'                  => '',
				'step'                 => '',
				'readonly'             => 0,
				'disabled'             => 0,
			),
			array(
				'key'          => 'field_ibv_villa_indicative_from_price',
				'label'        => __( 'Indicative from price (EUR / wk)', 'ibv' ),
				'name'         => 'villa_indicative_from_price',
				'type'         => 'number',
				'min'          => 0,
				'step'         => 1,
				'instructions' => __( 'Static fallback before live API prices.', 'ibv' ),
			),

			// ─── Tab: Offers ────────────────────────────────────────────
			array(
				'key'       => 'field_ibv_villa_tab_offers',
				'label'     => __( 'Offers', 'ibv' ),
				'type'      => 'tab',
				'placement' => 'left',
			),
			// Pass 3c-villa-offers — structured per-villa offers repeater.
			// The two legacy fields below feed the (legacy) Special Offers
			// page carousel and remain in place until that page is
			// refactored to aggregate from this repeater.
			array(
				'key'          => 'field_ibv_villa_offers',
				'label'        => __( 'Special Offers', 'ibv' ),
				'name'         => 'villa_offers',
				'type'         => 'repeater',
				'instructions' => __( 'Add active special offers for this villa. Offers automatically disappear from the site after their "Valid to" date passes.', 'ibv' ),
				'min'          => 0,
				'max'          => 0,
				'layout'       => 'block',
				'button_label' => __( 'Add offer', 'ibv' ),
				'sub_fields'   => array(
					array(
						'key'             => 'field_ibv_villa_offer_name',
						'label'           => __( 'Offer name', 'ibv' ),
						'name'            => 'offer_name',
						'type'            => 'text',
						'required'        => 1,
						'instructions'    => __( 'Marketing label, e.g. "Spring 4-night escape". Identifies the offer in enquiries.', 'ibv' ),
						'parent_repeater' => 'field_ibv_villa_offers',
					),
					array(
						'key'             => 'field_ibv_villa_offer_date_from',
						'label'           => __( 'Valid from', 'ibv' ),
						'name'            => 'offer_date_from',
						'type'            => 'date_picker',
						'required'        => 1,
						'display_format'  => 'j M Y',
						'return_format'   => 'Ymd',
						'first_day'       => 1,
						'parent_repeater' => 'field_ibv_villa_offers',
					),
					array(
						'key'             => 'field_ibv_villa_offer_date_to',
						'label'           => __( 'Valid to', 'ibv' ),
						'name'            => 'offer_date_to',
						'type'            => 'date_picker',
						'required'        => 1,
						'display_format'  => 'j M Y',
						'return_format'   => 'Ymd',
						'first_day'       => 1,
						'parent_repeater' => 'field_ibv_villa_offers',
					),
					array(
						'key'             => 'field_ibv_villa_offer_headline',
						'label'           => __( 'Headline', 'ibv' ),
						'name'            => 'offer_headline',
						'type'            => 'text',
						'required'        => 1,
						'maxlength'       => 30,
						'instructions'    => __( 'Short marketing line, ≤30 chars. e.g. "20% off" or "From €1,800/wk".', 'ibv' ),
						'parent_repeater' => 'field_ibv_villa_offers',
					),
					array(
						'key'             => 'field_ibv_villa_offer_description',
						'label'           => __( 'Description', 'ibv' ),
						'name'            => 'offer_description',
						'type'            => 'textarea',
						'rows'            => 3,
						'new_lines'       => 'wpautop',
						'instructions'    => __( 'Optional supporting copy, ~2 sentences.', 'ibv' ),
						'parent_repeater' => 'field_ibv_villa_offers',
					),
				),
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_565864063b06c',
				'label'                => 'Property Special Offers Text',
				'name'                 => 'property_special_offers_text',
				'aria-label'           => '',
				'type'                 => 'wysiwyg',
				'instructions'         => 'Legacy free-text offer copy used by the Special Offers page carousel. Use the structured "Special Offers" repeater above for new offers; this section will be retired once the SO page is migrated.',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'        => '',
				'tabs'                 => 'all',
				'toolbar'              => 'basic',
				'media_upload'         => 0,
				'delay'                => 0,
			),
			array(
				'allow_backendsearch'  => false,
				'show_column_filter'   => false,
				'allow_bulkedit'       => false,
				'allow_quickedit'      => false,
				'show_column'          => false,
				'show_column_weight'   => 1000,
				'show_column_sortable' => false,
				'key'                  => 'field_565867238ea4b',
				'label'                => 'Property Special Offer',
				'name'                 => 'property_special_offer_display',
				'aria-label'           => '',
				'type'                 => 'true_false',
				'instructions'         => 'Would you like to show this properties special offer around the site in the special offer carousel? If you don\'t tick this box the offer will be shown on this page only!',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'              => '',
				'default_value'        => 0,
				'ui'                   => 0,
				'ui_on_text'           => '',
				'ui_off_text'          => '',
			),

			// ─── Tab: Related ───────────────────────────────────────────
			array(
				'key'       => 'field_ibv_villa_tab_related',
				'label'     => __( 'Related', 'ibv' ),
				'type'      => 'tab',
				'placement' => 'left',
			),
			array(
				'key'           => 'field_ibv_villa_similar',
				'label'         => __( 'Similar villas', 'ibv' ),
				'name'          => 'villa_similar',
				'type'          => 'post_object',
				'post_type'     => array( 'villas' ),
				'multiple'      => 1,
				'min'           => 0,
				'max'           => 3,
				'return_format' => 'id',
				'instructions'  => __( 'Manual picks. Empty falls back to latest villas.', 'ibv' ),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'villas',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'acf_after_title',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'discussion',
			1 => 'comments',
			2 => 'categories',
			3 => 'tags',
			4 => 'send-trackbacks',
		),
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => false,
		'display_title'         => '',
		'allow_ai_access'       => false,
		'ai_description'        => '',
	) );
}

add_action( 'acf/init', 'ibv_register_villa_acf_fields', 15 );
